language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: pusnow
  password:
    secure: guyKiG5qPnWOwAcKoQP41z2KpVisj9Tkh3zUoEbJFKNvocLkAQZuXLHscD3N/nA5GzMJULKUyZPs5GoK0KKBmntUlJZBfuSi0sHDlsSmuAsB1Q3oJhkyNSJc4XV3ymdWy6lItnysoq9v/JXZDcQwrA2Urzy0JNDJ7YZk2jDQJA4BJmwuSBnhWC2yiA6PdZp8dnb8ntmZy0yxyLsf1pqvPNSs2YxStmB1/M7bHHaKL5GNA3fhlyefiYey+95XpR3SRhzWz7SnKMMsEFZ4E+qP8tfKa/6tvLTa5cA239AFGxyNhd/Kz/yIAKzJuL92gmNidngv5HhpN3nct7PQj1b64LXOGa3fkHoe1gcLVqarU9SthzTmKcXfO+D5i14cFj2MRGYgHluWVyHSis9LqEJv0i0FfB/IkDg44p9ex8SxocbzDIpHmYJzVKVUp1uHGsM+UgDG9LQGhtRhFoCDOLIEQw5FWWZbh8ygREqR12wPalEY/KY+Io+v9gOXHqfjW5CWhAdTkMBUTo4xXyth7Bpf3IEjBCKcAfT3uEEOB/gKrHIfMF3X36Tp7sYfwz2YjGkdaJYEmBkCjgvEZL2wJJ9B2Y8EzT20SQyDfCguRARmzJzGTM9D6+uSUbcJe+om/MmjMtq5fhCFVLJqwVye5YG4Ez+jmxG+NvRZNNiwqgl0UCg=
  on:
    tags: false
    branch: master
