language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- python -m unittest discover
deploy:
  provider: pypi
  user: pusnow
  password:
    secure: g6rnqCnXkWEPpPAYM5sknVoiVuPJ4Mzz2Ojzd2xzMBfBasMBMuipTxMbFLys1BKmyYK/ikpYVNoZMiLNbwe0riTxpgeAVqxS/kILkFyAAJd3NYWpdzlyU22UgZpAfKut5VI5pfWApug/JQFRSUnZyBcpfzxI5cqvNcavBzE1Oe2aVvxZm3Ggk7Za0Rrgr0oodfs+SOz1P7KPOeSqDPXkd6epBQIBrkOW6MiRM48E9XWFcq+1af4cvphvBl2jQ3DHMHh1s1SDmp46MVHENWNG9WqVUA7ELEHUxyY1dVU2IXzigb0+Mj5jLbtMKxM4SsAwqInjkkw+QoZn0YcEXy2b9H/agG8/L+qpuRR4nH7UzgrXkPXFSMEeDtA7rCgnt74aojJBncxVw0xnbwa8OhzBRqCansPMTChn4mT/SYFWailSF5k4zuf+ecGcnJsyDxOpyi9vtWySgghzy70NLKltM2pm+Dpf7vUfe+90BuuMlWm2sKATExSVEhhaesHcrNw/tQzwESsBH4kyCQ8yCsIYN2G3XS9LPLTT0/YPhHYmiehEUe/buQJ70cGJOd0haURwTjccTUMC3pyeNVJMaqhOYRdPfRnjxO3E0r189/DnIlqdAF7J6aAXZBAGoyIsSxzepIhos4ljZwaft/kWrhjyZEUdvg1o/BQ+/TIau4EGLUI=
  on:
    tags: true